[keyboard]
name = "Macropad_V5"
product_name = "Macropad_V5"
vendor_id = 0x4E41
product_id = 0x0000
manufacturer = "Nahuel"
chip = "nrf52840"

[layout]
rows = 12
cols = 8
layers = 4
keymap = [
[
    ["G", "G", "G", "G", "G", "G", "G","_"],
    ["D", "D", "D", "D", "D", "D", "D","_"],
    ["V", "V", "V", "V", "V", "V", "V","_"],
    ["C", "C", "C", "C", "C", "C", "C","C"],
    ["X", "X", "X", "X", "X", "X", "X","X"],
    ["_", "_", "_", "_", "_", "_", "_","Z"],

    ["G", "G", "G", "G", "G", "G", "G","_"],
    ["D", "D", "D", "D", "D", "D", "D","_"],
    ["V", "V", "V", "V", "V", "V", "V","_"],
    ["C", "C", "C", "C", "C", "C", "C","C"],
    ["X", "X", "X", "X", "X", "X", "X","X"],
    ["_", "_", "_", "_", "_", "_", "_","Z"],
],
[
    ["G", "G", "G", "G", "G", "G", "G","_"],
    ["D", "D", "D", "D", "D", "D", "D","_"],
    ["V", "V", "V", "V", "V", "V", "V","_"],
    ["C", "C", "C", "C", "C", "C", "C","C"],
    ["X", "X", "X", "X", "X", "X", "X","X"],
    ["_", "_", "_", "_", "_", "_", "_","Z"],

    ["G", "G", "G", "G", "G", "G", "G","_"],
    ["D", "D", "D", "D", "D", "D", "D","_"],
    ["V", "V", "V", "V", "V", "V", "V","_"],
    ["C", "C", "C", "C", "C", "C", "C","C"],
    ["X", "X", "X", "X", "X", "X", "X","X"],
    ["_", "_", "_", "_", "_", "_", "_","Z"],
],
[
    ["G", "G", "G", "G", "G", "G", "G","_"],
    ["D", "D", "D", "D", "D", "D", "D","_"],
    ["V", "V", "V", "V", "V", "V", "V","_"],
    ["C", "C", "C", "C", "C", "C", "C","C"],
    ["X", "X", "X", "X", "X", "X", "X","X"],
    ["_", "_", "_", "_", "_", "_", "_","Z"],

    ["G", "G", "G", "G", "G", "G", "G","_"],
    ["D", "D", "D", "D", "D", "D", "D","_"],
    ["V", "V", "V", "V", "V", "V", "V","_"],
    ["C", "C", "C", "C", "C", "C", "C","C"],
    ["X", "X", "X", "X", "X", "X", "X","X"],
    ["_", "_", "_", "_", "_", "_", "_","Z"],
],
[
    ["G", "G", "G", "G", "G", "G", "G","_"],
    ["D", "D", "D", "D", "D", "D", "D","_"],
    ["V", "V", "V", "V", "V", "V", "V","_"],
    ["C", "C", "C", "C", "C", "C", "C","C"],
    ["X", "X", "X", "X", "X", "X", "X","X"],
    ["_", "_", "_", "_", "_", "_", "_","Z"],

    ["G", "G", "G", "G", "G", "G", "G","_"],
    ["D", "D", "D", "D", "D", "D", "D","_"],
    ["V", "V", "V", "V", "V", "V", "V","_"],
    ["C", "C", "C", "C", "C", "C", "C","C"],
    ["X", "X", "X", "X", "X", "X", "X","X"],
    ["_", "_", "_", "_", "_", "_", "_","Z"],
],
]


[ble]
enabled = true

[behavior.morse.profiles]
HRM = { unilateral_tap = true, permissive_hold = true, hold_timeout = "250ms", gap_timeout = "120ms" }
FH = { hold_on_other_press = true, unilateral_tap = false, hold_timeout = "200ms", gap_timeout = "200ms" }
MRZ = { normal_mode = true, unilateral_tap = false, hold_timeout = "200ms", gap_timeout = "200ms" }

[split]
connection = "ble"

[split.central]
rows = 6
cols = 8
row_offset = 0
col_offset = 0

[split.central.matrix]
row_pins = ["P0_31", "P0_29", "P0_02", "P1_13","P1_15","P1_11"]
col_pins = ["P0_24","P1_00","P0_11","P1_04","P1_06","P0_09","P0_10","P0_22"]

[[split.peripheral]]
rows = 6
cols = 8
row_offset = 6
col_offset = 0

[split.peripheral.matrix]
row_pins = ["P0_31", "P0_29", "P0_02", "P1_13","P1_15","P1_11"]
col_pins = ["P0_24","P1_00","P0_11","P1_04","P1_06","P0_09","P0_10","P0_22"]

[host]
unlock_keys = [[0,0],[0,1]]
